---
title: "Policy Lapse EDA with explore"
author: "Tam Pham"
date: "`r Sys.Date()`"
output: html_document
editor_options: 
  chunk_output_type: console
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(cache = TRUE, warning = FALSE,
                      message = FALSE, echo = TRUE, dpi = 180,
                      fig.width = 8, fig.height = 5,
                      digits = 3)

library(tidyverse)
library(explore)
```

## Data

```{r include=FALSE}
policy <-
readxl::read_xlsx("../data/PolicyLapse.xlsx")

policy <-
  policy %>%
  select(-is.logical,-c("ID","PaymentTerm0","DistributionChannel0","PolicyYear")) %>%
  mutate_if(is.character,factor) %>%
  mutate(Lapsed = as.logical(as.integer(Lapsed=="Lapsed")))
```

## Explore
## * Shiny App -----

```{r}
policy %>%
  explore()
```

## * Describe -----

```{r}
policy %>%
  describe_all()

policy %>%
  describe_cat(DistributionChannel)
```

## * Explore All Variables ----

```{r}
policy %>%
    explore_all(
        target = Lapsed,
        ncol   = 3,
        split = FALSE
    )
```


## * Explore Bivariate Plot ----

```{r}
policy %>%
    explore(
        target = Lapsed,
        var    = Occupation,
        var2   = PO_Sex
    )
```
